# Generated by Django 5.0.1 on 2026-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(help_text='Brief summary for listings', max_length=300)),
                ('content', models.TextField(help_text='Full blog post content (HTML allowed)')),
                ('author_name', models.CharField(default='Gregory Woodruff', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(help_text='Main page content (HTML allowed)')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('show_in_navigation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('project_type', models.CharField(choices=[('HEALTHCARE', 'Healthcare Analytics'), ('EDUCATION', 'Educational Platform'), ('BUSINESS', 'Business Application'), ('MIGRATION', 'Cloud Migration'), ('INTEGRATION', 'System Integration'), ('OTHER', 'Other')], default='BUSINESS', max_length=20)),
                ('client_name', models.CharField(blank=True, help_text='Can be left blank for confidentiality', max_length=200)),
                ('short_description', models.CharField(max_length=255)),
                ('full_description', models.TextField(help_text='Detailed project description (HTML allowed)')),
                ('technologies_used', models.CharField(help_text='Comma-separated (Azure, Django, PostgreSQL, etc.)', max_length=500)),
                ('project_url', models.URLField(blank=True, help_text='Live project URL if public')),
                ('case_study_url', models.URLField(blank=True, help_text='Link to detailed case study')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Item',
                'verbose_name_plural': 'Portfolio Items',
                'ordering': ['-completion_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('AZURE', 'Azure Consulting'), ('M365', 'Microsoft 365'), ('MIGRATION', 'Cloud Migration'), ('SUPPORT', 'Technical Support'), ('TRAINING', 'Training & Education'), ('CUSTOM', 'Custom Development')], default='AZURE', max_length=20)),
                ('short_description', models.CharField(help_text='Brief description for cards/listings', max_length=255)),
                ('full_description', models.TextField(help_text='Detailed service description (HTML allowed)')),
                ('icon_class', models.CharField(blank=True, help_text="CSS icon class (e.g., 'fas fa-cloud')", max_length=100)),
                ('pricing_info', models.CharField(blank=True, help_text="e.g., 'Starting at $150/hour'", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
